name: Terraform

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - stage
        - prod

env:
  ENVIRONMENT: dev #${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || (github.ref_name == 'release/dev' && 'dev' || github.ref_name == 'release/stage' && 'stage' || 'prod') }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      terraform_changed: ${{ steps.filter.outputs.terraform }}
      argocd_changed: ${{ steps.filter.outputs.argocd }}
    steps:
    - uses: actions/checkout@v4
    - id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: |
          terraform:
            - 'infrastructure/terraform/**'
          argocd:
            - 'infrastructure/argo-cd/**'

  # Step 1: Terraform Apply
  terraform:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.terraform_changed == 'true'

    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Terraform Init
      working-directory: infrastructure/terraform
      run: terraform init -upgrade

    - name: Select Terraform Workspace
      working-directory: infrastructure/terraform
      run: terraform workspace select -or-create=true $ENVIRONMENT

    - name: Terraform Apply
      working-directory: infrastructure/terraform
      env:
        TF_IN_AUTOMATION: true
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_NAME: ${{ secrets.DB_NAME }}
        SERVICE_ACCOUNT_NAME: ${{ secrets.SERVICE_ACCOUNT_NAME }}
        ENV_PREFIX: ${{ env.ENVIRONMENT }}
      run: |
        terraform apply -auto-approve -input=false \
          -var="aws_account_id=$AWS_ACCOUNT_ID" \
          -var="region=$REGION" \
          -var="cluster_name=$CLUSTER_NAME" \
          -var="db_username=$DB_USERNAME" \
          -var="db_name=$DB_NAME" \
          -var="service_account_name=$SERVICE_ACCOUNT_NAME" \
          -var="ENV_PREFIX=$ENV_PREFIX"

  # Step 2: configure argocd
  Argocd:
    runs-on: ubuntu-latest
    needs:
    - detect-changes
    - terraform
    if: |
      needs.detect-changes.outputs.argocd_changed == 'true' &&
      (needs.terraform.result == 'success' || needs.terraform.result == 'skipped')

    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Terraform Init
      working-directory: infrastructure/argo-cd
      run: terraform init -upgrade

    - name: Terraform Apply
      working-directory: infrastructure/argo-cd
      env:
        TF_IN_AUTOMATION: true
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      run: |
        terraform apply -auto-approve -input=false \
          -var="aws_account_id=$AWS_ACCOUNT_ID" \
          -var="region=$REGION" \
          -var="cluster_name=$CLUSTER_NAME" 

########
#second version
name: Terraform

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - stage
        - prod

env:
  ENVIRONMENT: dev

jobs:
  # Detect what changed
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      terraform_changed: ${{ steps.filter.outputs.terraform }}
      argocd_changed: ${{ steps.filter.outputs.argocd }}
      both_changed: ${{ steps.check_both.outputs.both }}
    steps:
    - uses: actions/checkout@v4
    - id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: |
          terraform:
            - 'infrastructure/terraform/**'
          argocd:
            - 'infrastructure/argo-cd/**'

    - id: check_both
      run: |
        if [[ "${{ steps.filter.outputs.terraform }}" == "true" && "${{ steps.filter.outputs.argocd }}" == "true" ]]; then
          echo "both=true" >> $GITHUB_OUTPUT
        else
          echo "both=false" >> $GITHUB_OUTPUT
        fi

  # Step 1: Terraform Apply (runs only if terraform files changed)
  terraform:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.terraform_changed == 'true'

    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Terraform Init
      working-directory: infrastructure/terraform
      run: terraform init -upgrade

    - name: Select Terraform Workspace
      working-directory: infrastructure/terraform
      run: terraform workspace select -or-create=true $ENVIRONMENT

    - name: Terraform Apply
      working-directory: infrastructure/terraform
      env:
        TF_IN_AUTOMATION: true
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_NAME: ${{ secrets.DB_NAME }}
        SERVICE_ACCOUNT_NAME: ${{ secrets.SERVICE_ACCOUNT_NAME }}
        ENV_PREFIX: ${{ env.ENVIRONMENT }}
      run: |
        terraform apply -auto-approve -input=false \
          -var="aws_account_id=$AWS_ACCOUNT_ID" \
          -var="region=$REGION" \
          -var="cluster_name=$CLUSTER_NAME" \
          -var="db_username=$DB_USERNAME" \
          -var="db_name=$DB_NAME" \
          -var="service_account_name=$SERVICE_ACCOUNT_NAME" \
          -var="ENV_PREFIX=$ENV_PREFIX"

  # Dummy job to act as a gate when both changed
  terraform-gate:
    runs-on: ubuntu-latest
    needs:
    - detect-changes
    - terraform
    if: needs.detect-changes.outputs.both_changed == 'true'
    steps:
    - run: echo "Both terraform and argocd changed, terraform completed. Proceeding to argocd..."

  # Step 2: ArgoCD Apply - Independent path (only argocd changed)
  argocd-independent:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.argocd_changed == 'true' &&
      needs.detect-changes.outputs.both_changed == 'false'

    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Terraform Init
      working-directory: infrastructure/argo-cd
      run: terraform init -upgrade

    - name: Terraform Apply
      working-directory: infrastructure/argo-cd
      env:
        TF_IN_AUTOMATION: true
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      run: |
        terraform apply -auto-approve -input=false \
          -var="aws_account_id=$AWS_ACCOUNT_ID" \
          -var="region=$REGION" \
          -var="cluster_name=$CLUSTER_NAME"

  # Step 3: ArgoCD Apply - Dependent path (both changed, waits for terraform)
  argocd-dependent:
    runs-on: ubuntu-latest
    needs:
    - detect-changes
    - terraform-gate
    if: needs.detect-changes.outputs.both_changed == 'true'

    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Terraform Init
      working-directory: infrastructure/argo-cd
      run: terraform init -upgrade

    - name: Terraform Apply
      working-directory: infrastructure/argo-cd
      env:
        TF_IN_AUTOMATION: true
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      run: |
        terraform apply -auto-approve -input=false \
          -var="aws_account_id=$AWS_ACCOUNT_ID" \
          -var="region=$REGION" \
          -var="cluster_name=$CLUSTER_NAME"
